### ISSUE TITLE
About vox-5segments.onnx

### ISSUE THREAD

**Issue by harisreedhar** [instant-high/wav2lip-onnx-HQ#1]
Can you point me where i can find this orginal repo.

**Comment by instant-high** [comment]
You can find the original "Motion-supervised Co-Part Segmentation" repo here:
https://github.com/AliaksandrSiarohin/motion-cosegmentation

Take a look at the part_swap.py code line 133.
There are 3 different pretrained models for 5, 10 and 15 segments available

I didn't manage to get the original soft mask, so my result is more a rough version of hard mask.

**Comment by harisreedhar** [comment]
Thanks👍
