### ISSUE TITLE
Hallo, ich würde gerne eine Frage zu einer der Flaggen klären.

### ISSUE THREAD

**Issue by NeuroDonu** [instant-high/wav2lip-onnx-HQ#2]
Ich habe das Notepad, das unter dem [Link ](https://colab.research.google.com/drive/10WFQjVSR4-j2rN__MYUDEtB-dFouTQjv)verfügbar ist, benutzt und dieses Flag gesehen: --final_audio in Ihrer Datei [inference_onnxModel.py](https://github.com/instant-high/wav2lip-onnx-HQ/blob/main/inference_onnxModel.py). Können Sie bitte erklären, wozu das gut sein soll?

**Comment by instant-high** [comment]
If you use --final_audio, the --audio is used only for inference while the final output video will be muxed using --final_audio.

Eg. use a (separated) vocal track for inference and full music track for final result.

Or sometimes a voice may  be not suitable for wav2lip inference (rvc voice). In this case you can use original voice for inference and the cloned voice as final result.
