### ISSUE TITLE
pls update code to auto detect one face in video!

### ISSUE THREAD

**Issue by linhcentrio** [instant-high/wav2lip-onnx-HQ#7]
pls update code to auto detect one face in video!

**Comment by instant-high** [comment]
When you start inference, it shows the first frame (or your cut_in position) Then you have to:

1. crop final output or press enter to leave unchanged.
2. select the specific target face if there is more than one face in your image or video. Or press enter for no selection.

Selections are made by drawing a rectangle while pressing left mouse button and then press enter.

So you can simply press enter on both previews without seletion
